
# REGISTER
POST http://localhost:3000/users/register HTTP/1.1
content-type: application/json

{
    "username": "johndoe",
    "password": "somepass",
    "passwordAgain" : "somepass"
}

###
# LOGIN
POST http://localhost:3000/users/login HTTP/1.1
content-type: application/json

{
    "username": "johndoe",
    "password": "somepass"
}
